import pdb
from Node import *
import sys

def traverse(root, callback):
    """
    Walk the AST generated by the swim parser, starting with the
    SetList Node
    """
    callback(root)
#yield root, callback(root)
    #pdb.set_trace()
    if root.children:
        for child in root.children:
            traverse(child, callback)
    #if isinstance(Node, SetList):
    
def get_all_descendants(root):
    print "hi"
    #for n in traverse(root, lambda x: sys.stdout.write(str(x) + '\n')):
     #   yield n

if __name__=="__main__":
    import swim_parser
    p = swim_parser.parser
    #running parser will generate a SetList node containing all other Nodes.
    res = parser.parse("10x100")
    traverse(res,lambda x: None) 
